name: Build and Release Iconset

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build TAK Data Package
      run: |
        mkdir -p datapackage/iconsets
        ./scripts/create_TAKDataPackage.sh
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Iconset-Package.zip
          datapackage/iconsets/GEMA NZEM Symbology Set.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}